# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/darta/AppData/Local/Temp/loading_screenteYorX.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Loading_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(786, 481)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(-1, -1, 8, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.f_edit = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_edit.sizePolicy().hasHeightForWidth())
        self.f_edit.setSizePolicy(sizePolicy)
        self.f_edit.setMinimumSize(QtCore.QSize(764, 459))
        self.f_edit.setMaximumSize(QtCore.QSize(764, 459))
        self.f_edit.setStyleSheet("QLabel#edit_arrows {\n"
"    background-color: #20242d;\n"
"    font: 40pt \"Traffic Arrows 2 Medium normal\";\n"
"    color: rgb(238, 238, 238);\n"
"    border-radius: 25px;\n"
"\n"
"}\n"
"\n"
"QFrame#f_edit {\n"
"    background-color: #2C303A;\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QFrame#f_error_combine {\n"
"    background-color: #20242d;\n"
"    border-top-right-radius: 25px;\n"
"    border-bottom-right-radius: 25px;\n"
"}\n"
"\n"
"QFrame#f_empty_side {\n"
"    background-color:#20242d;\n"
"    border-top-left-radius: 25px;\n"
"    border-bottom-left-radius: 25px;\n"
"}\n"
"\n"
"")
        self.f_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit.setObjectName("f_edit")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.f_edit)
        self.verticalLayout.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout.setSpacing(11)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.f_edit)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/junc_loading/Bens/Work/Python/JUNC/git/JUNC/junc gif - 2.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout.addWidget(self.f_edit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
