# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/darta/AppData/Local/Temp/window_arrows_with_complexcZLDbS.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Arrow_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(786, 481)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.f_edit = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_edit.sizePolicy().hasHeightForWidth())
        self.f_edit.setSizePolicy(sizePolicy)
        self.f_edit.setMinimumSize(QtCore.QSize(764, 459))
        self.f_edit.setMaximumSize(QtCore.QSize(764, 459))
        self.f_edit.setStyleSheet("QLabel#edit_arrows {\n"
"    background-color: #20242d;\n"
"    font: 40pt \"Traffic Arrows 2 Medium normal\";\n"
"    color: rgb(238, 238, 238);\n"
"    border-radius: 25px;\n"
"\n"
"}\n"
"\n"
"QFrame#f_edit {\n"
"    background-color: #2C303A;\n"
"    border-radius: 25px;\n"
"}\n"
"\n"
"QFrame#f_error_combine {\n"
"    background-color: #20242d;\n"
"    border-top-right-radius: 25px;\n"
"    border-bottom-right-radius: 25px;\n"
"}\n"
"\n"
"QFrame#f_empty_side {\n"
"    background-color:#20242d;\n"
"    border-top-left-radius: 25px;\n"
"    border-bottom-left-radius: 25px;\n"
"}\n"
"\n"
"")
        self.f_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit.setObjectName("f_edit")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.f_edit)
        self.verticalLayout.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.f_edit_toolbar = QtWidgets.QFrame(self.f_edit)
        self.f_edit_toolbar.setMaximumSize(QtCore.QSize(16777215, 62))
        self.f_edit_toolbar.setStyleSheet("QFrame#f_edit_toolbar{\n"
"    background-color: rgba(55, 62, 78, 100);\n"
"    border-top-left-radius: 25px;\n"
"    border-top-right-radius: 25px;\n"
"}")
        self.f_edit_toolbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_toolbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_toolbar.setObjectName("f_edit_toolbar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.f_edit_toolbar)
        self.horizontalLayout_3.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.f_edit_toolbar)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setContentsMargins(7, 0, 7, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.b_clear_all = QtWidgets.QPushButton(self.frame)
        self.b_clear_all.setMinimumSize(QtCore.QSize(40, 40))
        self.b_clear_all.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Icons-JUNC-1")
        font.setPointSize(15)
        self.b_clear_all.setFont(font)
        self.b_clear_all.setStyleSheet("QPushButton{\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: rgb(234, 94, 124);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(202, 81, 107);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(120, 48, 63);\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"color: rgb(120, 120, 120);\n"
"}")
        self.b_clear_all.setObjectName("b_clear_all")
        self.horizontalLayout_5.addWidget(self.b_clear_all, 0, QtCore.Qt.AlignVCenter)
        self.b_clear_combined = QtWidgets.QPushButton(self.frame)
        self.b_clear_combined.setMinimumSize(QtCore.QSize(40, 40))
        self.b_clear_combined.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Icons-JUNC-1")
        font.setPointSize(18)
        self.b_clear_combined.setFont(font)
        self.b_clear_combined.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: #c43e1c;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:#cf6644;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color:#802e18;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(120,120,120);\n"
"}")
        self.b_clear_combined.setIconSize(QtCore.QSize(10, 10))
        self.b_clear_combined.setObjectName("b_clear_combined")
        self.horizontalLayout_5.addWidget(self.b_clear_combined)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setStyleSheet("\n"
"background-color: rgba(184, 184, 184, 50);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.f_combine = QtWidgets.QFrame(self.frame)
        self.f_combine.setMinimumSize(QtCore.QSize(0, 40))
        self.f_combine.setStyleSheet("QFrame#f_combine {\n"
"    background-color: rgba(34, 117, 138, 30);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.f_combine.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_combine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_combine.setObjectName("f_combine")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.f_combine)
        self.horizontalLayout_9.setContentsMargins(5, 4, 5, 4)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.b_combine = QtWidgets.QPushButton(self.f_combine)
        self.b_combine.setMinimumSize(QtCore.QSize(40, 40))
        self.b_combine.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Icons-JUNC-1")
        font.setPointSize(15)
        self.b_combine.setFont(font)
        self.b_combine.setStyleSheet("QPushButton#b_combine{\n"
"background-color: rgba(0,0,0,0)\n"
";color: rgb(47, 119, 138);\n"
"}\n"
"\n"
"QPushButton#b_combine:hover{\n"
"color: rgb(44, 153, 180);\n"
"}\n"
"\n"
"QPushButton#b_combine:pressed{\n"
"color: rgb(24, 74, 87);\n"
"}")
        self.b_combine.setCheckable(True)
        self.b_combine.setObjectName("b_combine")
        self.horizontalLayout_9.addWidget(self.b_combine)
        self.f_combine_adds = QtWidgets.QFrame(self.f_combine)
        self.f_combine_adds.setMinimumSize(QtCore.QSize(0, 0))
        self.f_combine_adds.setMaximumSize(QtCore.QSize(16777215, 40))
        self.f_combine_adds.setStyleSheet("QFrame#f_combine_adds{\n"
"background-color: rgba(225, 225, 225, 30);\n"
"border-radius: 13px;\n"
"}")
        self.f_combine_adds.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_combine_adds.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_combine_adds.setObjectName("f_combine_adds")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.f_combine_adds)
        self.horizontalLayout_8.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.b_combine_accept = QtWidgets.QPushButton(self.f_combine_adds)
        self.b_combine_accept.setMinimumSize(QtCore.QSize(30, 30))
        self.b_combine_accept.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Icons-JUNC-1")
        font.setPointSize(12)
        self.b_combine_accept.setFont(font)
        self.b_combine_accept.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: #34a852;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #34ac52;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #25793a;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(161, 161, 161);\n"
"}")
        self.b_combine_accept.setCheckable(True)
        self.b_combine_accept.setObjectName("b_combine_accept")
        self.horizontalLayout_8.addWidget(self.b_combine_accept)
        self.b_combine_del = QtWidgets.QPushButton(self.f_combine_adds)
        self.b_combine_del.setMinimumSize(QtCore.QSize(30, 30))
        self.b_combine_del.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Icons-JUNC-1")
        font.setPointSize(12)
        self.b_combine_del.setFont(font)
        self.b_combine_del.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"background-color: rgba(0,0,0,0);\n"
"color:#fbbb04;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color: #ffd607;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color: #dda303;\n"
"}")
        self.b_combine_del.setCheckable(True)
        self.b_combine_del.setObjectName("b_combine_del")
        self.horizontalLayout_8.addWidget(self.b_combine_del)
        self.horizontalLayout_9.addWidget(self.f_combine_adds)
        self.horizontalLayout_5.addWidget(self.f_combine)
        self.horizontalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.f_window_name_arrows = QtWidgets.QFrame(self.f_edit_toolbar)
        self.f_window_name_arrows.setStyleSheet("\n"
"QLabel#window_name_arrows{background-color: rgba(239, 239, 239,50);\n"
"font: 14pt \"Rubik\";\n"
"color: rgb(159, 159, 159);\n"
"border-radius: 7px;}")
        self.f_window_name_arrows.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_window_name_arrows.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_window_name_arrows.setObjectName("f_window_name_arrows")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.f_window_name_arrows)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.window_name_arrows = QtWidgets.QLabel(self.f_window_name_arrows)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.window_name_arrows.sizePolicy().hasHeightForWidth())
        self.window_name_arrows.setSizePolicy(sizePolicy)
        self.window_name_arrows.setMaximumSize(QtCore.QSize(300, 16777215))
        self.window_name_arrows.setStyleSheet("padding: 5px;")
        self.window_name_arrows.setAlignment(QtCore.Qt.AlignCenter)
        self.window_name_arrows.setObjectName("window_name_arrows")
        self.horizontalLayout_7.addWidget(self.window_name_arrows)
        self.horizontalLayout_3.addWidget(self.f_window_name_arrows, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.frame_2 = QtWidgets.QFrame(self.f_edit_toolbar)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.b_accept = QtWidgets.QPushButton(self.frame_2)
        self.b_accept.setMinimumSize(QtCore.QSize(50, 50))
        self.b_accept.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Icons-JUNC-1")
        font.setPointSize(15)
        self.b_accept.setFont(font)
        self.b_accept.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: rgb(51, 152, 143);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgb(37, 113, 105);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgb(25, 79, 73);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(120,120,120);\n"
"}")
        self.b_accept.setObjectName("b_accept")
        self.horizontalLayout_6.addWidget(self.b_accept)
        self.b_close = QtWidgets.QPushButton(self.frame_2)
        self.b_close.setMinimumSize(QtCore.QSize(50, 50))
        self.b_close.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Icons-JUNC-1")
        font.setPointSize(15)
        self.b_close.setFont(font)
        self.b_close.setStyleSheet("QPushButton {\n"
"    background-color: rgba(0,0,0,0);\n"
"    color: rgb(182, 75, 77);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: rgba(165, 0, 41, 200);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: rgba(165, 0, 41, 110);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    color: rgb(120, 120, 120);\n"
"}")
        self.b_close.setObjectName("b_close")
        self.horizontalLayout_6.addWidget(self.b_close)
        self.horizontalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.f_edit_toolbar)
        self.f_edit_labels = QtWidgets.QFrame(self.f_edit)
        self.f_edit_labels.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_labels.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_labels.setObjectName("f_edit_labels")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.f_edit_labels)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.f_combined_arrows = QtWidgets.QFrame(self.f_edit_labels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_combined_arrows.sizePolicy().hasHeightForWidth())
        self.f_combined_arrows.setSizePolicy(sizePolicy)
        self.f_combined_arrows.setMinimumSize(QtCore.QSize(0, 0))
        self.f_combined_arrows.setMaximumSize(QtCore.QSize(550, 0))
        self.f_combined_arrows.setStyleSheet("QLabel#edit_combined_arrows {\n"
"    background-color: rgba(38, 97, 112, 120);\n"
"    font: 40pt \"Traffic Arrows 2 Medium normal\";\n"
"    color: rgb(238, 238, 238);\n"
"}\n"
"\n"
"QFrame#f_error_combine {\n"
"    background-color: rgba(38, 97, 112, 120);\n"
"    border-top-right-radius: 25px;\n"
"    border-bottom-right-radius: 25px;\n"
"}\n"
"\n"
"QFrame#f_empty_side_combined {\n"
"\n"
"    background-color: rgba(38, 97, 112, 120);\n"
"    border-top-left-radius: 25px;\n"
"    border-bottom-left-radius: 25px;\n"
"}")
        self.f_combined_arrows.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_combined_arrows.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_combined_arrows.setObjectName("f_combined_arrows")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.f_combined_arrows)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.f_empty_side_combined = QtWidgets.QFrame(self.f_combined_arrows)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_empty_side_combined.sizePolicy().hasHeightForWidth())
        self.f_empty_side_combined.setSizePolicy(sizePolicy)
        self.f_empty_side_combined.setMinimumSize(QtCore.QSize(60, 120))
        self.f_empty_side_combined.setMaximumSize(QtCore.QSize(60, 120))
        self.f_empty_side_combined.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_empty_side_combined.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_empty_side_combined.setObjectName("f_empty_side_combined")
        self.horizontalLayout_14.addWidget(self.f_empty_side_combined, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.edit_combined_arrows = QtWidgets.QLabel(self.f_combined_arrows)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_combined_arrows.sizePolicy().hasHeightForWidth())
        self.edit_combined_arrows.setSizePolicy(sizePolicy)
        self.edit_combined_arrows.setMinimumSize(QtCore.QSize(300, 120))
        self.edit_combined_arrows.setMaximumSize(QtCore.QSize(300, 120))
        self.edit_combined_arrows.setText("")
        self.edit_combined_arrows.setScaledContents(True)
        self.edit_combined_arrows.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_combined_arrows.setIndent(0)
        self.edit_combined_arrows.setOpenExternalLinks(False)
        self.edit_combined_arrows.setObjectName("edit_combined_arrows")
        self.horizontalLayout_14.addWidget(self.edit_combined_arrows)
        self.f_error_combine = QtWidgets.QFrame(self.f_combined_arrows)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_error_combine.sizePolicy().hasHeightForWidth())
        self.f_error_combine.setSizePolicy(sizePolicy)
        self.f_error_combine.setMinimumSize(QtCore.QSize(60, 120))
        self.f_error_combine.setMaximumSize(QtCore.QSize(60, 120))
        self.f_error_combine.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_error_combine.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_error_combine.setObjectName("f_error_combine")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.f_error_combine)
        self.horizontalLayout_13.setContentsMargins(0, 12, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.error_combine = QtWidgets.QLabel(self.f_error_combine)
        self.error_combine.setEnabled(True)
        self.error_combine.setMinimumSize(QtCore.QSize(40, 40))
        self.error_combine.setMaximumSize(QtCore.QSize(40, 40))
        self.error_combine.setStyleSheet("QLabel {\n"
"    background-color: rgb(182, 75, 77);\n"
"    color: rgbab(144, 32, 53,255);\n"
"    border-radius: 15px;\n"
"\n"
"    font: 57 18pt \"Traffic Arrows 2 Medium normal\";\n"
"}\n"
"\n"
"\n"
"")
        self.error_combine.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.error_combine.setObjectName("error_combine")
        self.horizontalLayout_13.addWidget(self.error_combine, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_14.addWidget(self.f_error_combine)
        self.verticalLayout_14.addWidget(self.f_combined_arrows, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.f_edit_arrows = QtWidgets.QFrame(self.f_edit_labels)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_edit_arrows.sizePolicy().hasHeightForWidth())
        self.f_edit_arrows.setSizePolicy(sizePolicy)
        self.f_edit_arrows.setMinimumSize(QtCore.QSize(100, 0))
        self.f_edit_arrows.setMaximumSize(QtCore.QSize(700, 180))
        self.f_edit_arrows.setStyleSheet("")
        self.f_edit_arrows.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_arrows.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_arrows.setObjectName("f_edit_arrows")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.f_edit_arrows)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.edit_arrows = QtWidgets.QLabel(self.f_edit_arrows)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_arrows.sizePolicy().hasHeightForWidth())
        self.edit_arrows.setSizePolicy(sizePolicy)
        self.edit_arrows.setMinimumSize(QtCore.QSize(550, 120))
        self.edit_arrows.setMaximumSize(QtCore.QSize(500, 120))
        self.edit_arrows.setScaledContents(True)
        self.edit_arrows.setAlignment(QtCore.Qt.AlignCenter)
        self.edit_arrows.setObjectName("edit_arrows")
        self.verticalLayout_2.addWidget(self.edit_arrows)
        self.verticalLayout_14.addWidget(self.f_edit_arrows)
        self.verticalLayout.addWidget(self.f_edit_labels, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.f_edit_keys = QtWidgets.QFrame(self.f_edit)
        self.f_edit_keys.setStyleSheet("QSpinBox {\n"
"    font: 1pt \"Rubik\";\n"
"    color: rgb(48, 54, 69);\n"
"    border-radius: 45px;\n"
"    background-color: rgba(227, 227, 0, 0);\n"
"    width: 0px;\n"
"    height: 90px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-bottom: 12px solid rgb(48, 54, 69);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(100, 100, 100);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow:pressed {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-bottom: 12px solid rgb(7, 72, 67);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(11, 108, 103);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-top: 12px solid rgb(48, 54, 69);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(100, 100, 100);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(128, 0, 32);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow:pressed {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-top: 12px solid rgb(77, 0, 19);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow:disabled {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-bottom: 12px solid rgb(114, 114, 114);\n"
"}\n"
"\n"
"QSpinBox::up-button:disabled {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-button:disabled {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(80, 80, 80);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow:disabled {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-top: 12px solid rgb(114, 114, 114);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.f_edit_keys.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_keys.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_keys.setObjectName("f_edit_keys")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.f_edit_keys)
        self.horizontalLayout_4.setSpacing(30)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.f_edit_l = QtWidgets.QFrame(self.f_edit_keys)
        self.f_edit_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.f_edit_l.setStyleSheet("")
        self.f_edit_l.setInputMethodHints(QtCore.Qt.ImhNone)
        self.f_edit_l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_l.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_l.setObjectName("f_edit_l")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.f_edit_l)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.b_edit_l = QtWidgets.QPushButton(self.f_edit_l)
        self.b_edit_l.setMinimumSize(QtCore.QSize(50, 50))
        self.b_edit_l.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_edit_l.setFont(font)
        self.b_edit_l.setStyleSheet("QPushButton{background-color: rgb(55, 62, 78);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_edit_l.setObjectName("b_edit_l")
        self.verticalLayout_3.addWidget(self.b_edit_l, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_l = QtWidgets.QSpinBox(self.f_edit_l)
        self.sp_l.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_l.setStyleSheet("")
        self.sp_l.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_l.setMaximum(9)
        self.sp_l.setObjectName("sp_l")
        self.verticalLayout_3.addWidget(self.sp_l, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addWidget(self.f_edit_l)
        self.f_edit_rl = QtWidgets.QFrame(self.f_edit_keys)
        self.f_edit_rl.setStyleSheet("")
        self.f_edit_rl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_rl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_rl.setObjectName("f_edit_rl")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.f_edit_rl)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.b_edit_rl = QtWidgets.QPushButton(self.f_edit_rl)
        self.b_edit_rl.setMinimumSize(QtCore.QSize(50, 50))
        self.b_edit_rl.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_edit_rl.setFont(font)
        self.b_edit_rl.setStyleSheet("QPushButton{background-color: rgb(55, 62, 78);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_edit_rl.setObjectName("b_edit_rl")
        self.verticalLayout_4.addWidget(self.b_edit_rl, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_rl = QtWidgets.QSpinBox(self.f_edit_rl)
        self.sp_rl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_rl.setStyleSheet("")
        self.sp_rl.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_rl.setMaximum(1)
        self.sp_rl.setObjectName("sp_rl")
        self.verticalLayout_4.addWidget(self.sp_rl)
        self.horizontalLayout_4.addWidget(self.f_edit_rl)
        self.f_edit_tl = QtWidgets.QFrame(self.f_edit_keys)
        self.f_edit_tl.setStyleSheet("")
        self.f_edit_tl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_tl.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_tl.setObjectName("f_edit_tl")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.f_edit_tl)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.b_edit_tl = QtWidgets.QPushButton(self.f_edit_tl)
        self.b_edit_tl.setMinimumSize(QtCore.QSize(50, 50))
        self.b_edit_tl.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_edit_tl.setFont(font)
        self.b_edit_tl.setStyleSheet("QPushButton{background-color: rgb(55, 62, 78);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_edit_tl.setObjectName("b_edit_tl")
        self.verticalLayout_5.addWidget(self.b_edit_tl, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_tl = QtWidgets.QSpinBox(self.f_edit_tl)
        self.sp_tl.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_tl.setStyleSheet("")
        self.sp_tl.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_tl.setMaximum(1)
        self.sp_tl.setObjectName("sp_tl")
        self.verticalLayout_5.addWidget(self.sp_tl)
        self.horizontalLayout_4.addWidget(self.f_edit_tl)
        self.f_edit_t = QtWidgets.QFrame(self.f_edit_keys)
        self.f_edit_t.setStyleSheet("")
        self.f_edit_t.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_t.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_t.setObjectName("f_edit_t")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.f_edit_t)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.b_edit_t = QtWidgets.QPushButton(self.f_edit_t)
        self.b_edit_t.setMinimumSize(QtCore.QSize(50, 50))
        self.b_edit_t.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_edit_t.setFont(font)
        self.b_edit_t.setStyleSheet("QPushButton{background-color: rgb(55, 62, 78);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_edit_t.setObjectName("b_edit_t")
        self.verticalLayout_6.addWidget(self.b_edit_t, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_t = QtWidgets.QSpinBox(self.f_edit_t)
        self.sp_t.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_t.setStyleSheet("")
        self.sp_t.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_t.setMaximum(9)
        self.sp_t.setObjectName("sp_t")
        self.verticalLayout_6.addWidget(self.sp_t)
        self.horizontalLayout_4.addWidget(self.f_edit_t)
        self.f_arrows_combined_buttons = QtWidgets.QFrame(self.f_edit_keys)
        self.f_arrows_combined_buttons.setMinimumSize(QtCore.QSize(0, 0))
        self.f_arrows_combined_buttons.setSizeIncrement(QtCore.QSize(0, 0))
        self.f_arrows_combined_buttons.setStyleSheet("QSpinBox {\n"
"    font: 1pt \'Rubik\';\n"
"    color: rgb(48, 54, 69);\n"
"    border-radius: 45px;\n"
"    background-color: rgba(227, 227, 0, 0);\n"
"    width: 0px;\n"
"    height: 75px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-bottom: 12px solid rgba(227, 227, 0, 0);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: white;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-button:hover {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(100, 100, 100);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::up-arrow:pressed {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-bottom: 12px solid rgba(227, 227, 0, 0);\n"
"}\n"
"\n"
"QSpinBox::down-button:pressed {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(70,70,70);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-top: 12px solid rgba(227, 227, 0, 0);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(80, 80,80);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(100, 100, 100);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed {\n"
"    width: 55px;\n"
"    height: 35px;\n"
"    background-color: rgb(60,60,60);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSpinBox::down-arrow:pressed {\n"
"    border-left: 6px solid rgba(227, 227, 0, 0);\n"
"    border-right: 6px solid rgba(227, 227, 0, 0);\n"
"    border-top: 12px solid rgba(227, 227, 0, 0);\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}")
        self.f_arrows_combined_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_arrows_combined_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_arrows_combined_buttons.setObjectName("f_arrows_combined_buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.f_arrows_combined_buttons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.f_comb_l = QtWidgets.QFrame(self.f_arrows_combined_buttons)
        self.f_comb_l.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.f_comb_l.setStyleSheet("")
        self.f_comb_l.setInputMethodHints(QtCore.Qt.ImhNone)
        self.f_comb_l.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_comb_l.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_comb_l.setObjectName("f_comb_l")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.f_comb_l)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(12)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.b_comb_l = QtWidgets.QPushButton(self.f_comb_l)
        self.b_comb_l.setMinimumSize(QtCore.QSize(50, 50))
        self.b_comb_l.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_comb_l.setFont(font)
        self.b_comb_l.setStyleSheet("QPushButton{background-color: rgba(34, 117, 138, 150);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_comb_l.setObjectName("b_comb_l")
        self.verticalLayout_15.addWidget(self.b_comb_l, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_l_comb = QtWidgets.QSpinBox(self.f_comb_l)
        self.sp_l_comb.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_l_comb.setStyleSheet("")
        self.sp_l_comb.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_l_comb.setMinimum(0)
        self.sp_l_comb.setMaximum(1)
        self.sp_l_comb.setSingleStep(1)
        self.sp_l_comb.setObjectName("sp_l_comb")
        self.verticalLayout_15.addWidget(self.sp_l_comb, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.f_comb_l)
        self.f_comb_t = QtWidgets.QFrame(self.f_arrows_combined_buttons)
        self.f_comb_t.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.f_comb_t.setStyleSheet("")
        self.f_comb_t.setInputMethodHints(QtCore.Qt.ImhNone)
        self.f_comb_t.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_comb_t.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_comb_t.setObjectName("f_comb_t")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.f_comb_t)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(12)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.b_comb_t = QtWidgets.QPushButton(self.f_comb_t)
        self.b_comb_t.setMinimumSize(QtCore.QSize(50, 50))
        self.b_comb_t.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_comb_t.setFont(font)
        self.b_comb_t.setStyleSheet("QPushButton{background-color: rgba(34, 117, 138, 150);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_comb_t.setObjectName("b_comb_t")
        self.verticalLayout_17.addWidget(self.b_comb_t, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_t_comb = QtWidgets.QSpinBox(self.f_comb_t)
        self.sp_t_comb.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_t_comb.setStyleSheet("")
        self.sp_t_comb.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_t_comb.setMinimum(0)
        self.sp_t_comb.setMaximum(1)
        self.sp_t_comb.setSingleStep(1)
        self.sp_t_comb.setObjectName("sp_t_comb")
        self.verticalLayout_17.addWidget(self.sp_t_comb, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.f_comb_t)
        self.f_comb_r = QtWidgets.QFrame(self.f_arrows_combined_buttons)
        self.f_comb_r.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.f_comb_r.setStyleSheet("")
        self.f_comb_r.setInputMethodHints(QtCore.Qt.ImhNone)
        self.f_comb_r.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_comb_r.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_comb_r.setObjectName("f_comb_r")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.f_comb_r)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(12)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.b_comb_r = QtWidgets.QPushButton(self.f_comb_r)
        self.b_comb_r.setMinimumSize(QtCore.QSize(50, 50))
        self.b_comb_r.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_comb_r.setFont(font)
        self.b_comb_r.setStyleSheet("QPushButton{background-color: rgba(34, 117, 138, 150);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_comb_r.setObjectName("b_comb_r")
        self.verticalLayout_16.addWidget(self.b_comb_r, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_r_comb = QtWidgets.QSpinBox(self.f_comb_r)
        self.sp_r_comb.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_r_comb.setStyleSheet("")
        self.sp_r_comb.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_r_comb.setMinimum(0)
        self.sp_r_comb.setMaximum(1)
        self.sp_r_comb.setSingleStep(1)
        self.sp_r_comb.setObjectName("sp_r_comb")
        self.verticalLayout_16.addWidget(self.sp_r_comb, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_2.addWidget(self.f_comb_r)
        self.horizontalLayout_4.addWidget(self.f_arrows_combined_buttons)
        self.f_edit_tr = QtWidgets.QFrame(self.f_edit_keys)
        self.f_edit_tr.setStyleSheet("")
        self.f_edit_tr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_tr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_tr.setObjectName("f_edit_tr")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.f_edit_tr)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.b_edit_tr = QtWidgets.QPushButton(self.f_edit_tr)
        self.b_edit_tr.setMinimumSize(QtCore.QSize(50, 50))
        self.b_edit_tr.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_edit_tr.setFont(font)
        self.b_edit_tr.setStyleSheet("QPushButton{background-color: rgb(55, 62, 78);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_edit_tr.setObjectName("b_edit_tr")
        self.verticalLayout_7.addWidget(self.b_edit_tr, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_tr = QtWidgets.QSpinBox(self.f_edit_tr)
        self.sp_tr.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_tr.setStyleSheet("")
        self.sp_tr.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_tr.setMaximum(1)
        self.sp_tr.setObjectName("sp_tr")
        self.verticalLayout_7.addWidget(self.sp_tr)
        self.horizontalLayout_4.addWidget(self.f_edit_tr)
        self.f_edit_a = QtWidgets.QFrame(self.f_edit_keys)
        self.f_edit_a.setStyleSheet("")
        self.f_edit_a.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_a.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_a.setObjectName("f_edit_a")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.f_edit_a)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.b_edit_a = QtWidgets.QPushButton(self.f_edit_a)
        self.b_edit_a.setMinimumSize(QtCore.QSize(50, 50))
        self.b_edit_a.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_edit_a.setFont(font)
        self.b_edit_a.setStyleSheet("QPushButton{background-color: rgb(55, 62, 78);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_edit_a.setObjectName("b_edit_a")
        self.verticalLayout_8.addWidget(self.b_edit_a, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_a = QtWidgets.QSpinBox(self.f_edit_a)
        self.sp_a.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_a.setStyleSheet("")
        self.sp_a.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_a.setMaximum(1)
        self.sp_a.setObjectName("sp_a")
        self.verticalLayout_8.addWidget(self.sp_a)
        self.horizontalLayout_4.addWidget(self.f_edit_a)
        self.f_edit_r = QtWidgets.QFrame(self.f_edit_keys)
        self.f_edit_r.setStyleSheet("")
        self.f_edit_r.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_r.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_r.setObjectName("f_edit_r")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.f_edit_r)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.b_edit_r = QtWidgets.QPushButton(self.f_edit_r)
        self.b_edit_r.setMinimumSize(QtCore.QSize(50, 50))
        self.b_edit_r.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_edit_r.setFont(font)
        self.b_edit_r.setStyleSheet("QPushButton{background-color: rgb(55, 62, 78);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_edit_r.setObjectName("b_edit_r")
        self.verticalLayout_9.addWidget(self.b_edit_r, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_r = QtWidgets.QSpinBox(self.f_edit_r)
        self.sp_r.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_r.setStyleSheet("")
        self.sp_r.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_r.setMaximum(9)
        self.sp_r.setObjectName("sp_r")
        self.verticalLayout_9.addWidget(self.sp_r)
        self.horizontalLayout_4.addWidget(self.f_edit_r)
        self.f_edit_sr = QtWidgets.QFrame(self.f_edit_keys)
        self.f_edit_sr.setStyleSheet("")
        self.f_edit_sr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_edit_sr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_edit_sr.setObjectName("f_edit_sr")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.f_edit_sr)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.b_edit_sr = QtWidgets.QPushButton(self.f_edit_sr)
        self.b_edit_sr.setMinimumSize(QtCore.QSize(50, 50))
        self.b_edit_sr.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Traffic Arrows")
        font.setPointSize(28)
        self.b_edit_sr.setFont(font)
        self.b_edit_sr.setStyleSheet("QPushButton{background-color: rgb(55, 62, 78);color: rgba(200,200,200,255);border-radius: 15px;}QPushButton:hover{color: rgba(155,168,182,220);}QPushButton:pressed{color: rgba(115,128,142,255);}QPushButton:disabled{color: rgb(120,120,120);}")
        self.b_edit_sr.setObjectName("b_edit_sr")
        self.verticalLayout_10.addWidget(self.b_edit_sr, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sp_sr = QtWidgets.QSpinBox(self.f_edit_sr)
        self.sp_sr.setEnabled(True)
        self.sp_sr.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.sp_sr.setStyleSheet("")
        self.sp_sr.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.sp_sr.setMaximum(1)
        self.sp_sr.setObjectName("sp_sr")
        self.verticalLayout_10.addWidget(self.sp_sr, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_4.addWidget(self.f_edit_sr)
        self.verticalLayout.addWidget(self.f_edit_keys, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.f_edit)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.b_clear_all.setText(_translate("Form", "a"))
        self.b_clear_combined.setText(_translate("Form", "i"))
        self.b_combine.setText(_translate("Form", "Y"))
        self.b_combine_accept.setText(_translate("Form", "h"))
        self.b_combine_del.setText(_translate("Form", "f"))
        self.window_name_arrows.setText(_translate("Form", "-"))
        self.b_accept.setText(_translate("Form", "b"))
        self.b_close.setText(_translate("Form", "V"))
        self.error_combine.setText(_translate("Form", "9"))
        self.edit_arrows.setText(_translate("Form", "..."))
        self.b_edit_l.setText(_translate("Form", "l"))
        self.b_edit_rl.setText(_translate("Form", "s"))
        self.b_edit_tl.setText(_translate("Form", "a"))
        self.b_edit_t.setText(_translate("Form", "t"))
        self.b_comb_l.setText(_translate("Form", "l"))
        self.b_comb_t.setText(_translate("Form", "t"))
        self.b_comb_r.setText(_translate("Form", "r"))
        self.b_edit_tr.setText(_translate("Form", "d"))
        self.b_edit_a.setText(_translate("Form", "w"))
        self.b_edit_r.setText(_translate("Form", "r"))
        self.b_edit_sr.setText(_translate("Form", "e"))
